name: Build and Push Siege Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # Runs every Sunday at midnight UTC

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.get-version.outputs.latest_version }}
      major_version: ${{ steps.get-version.outputs.major_version }}
      minor_version: ${{ steps.get-version.outputs.minor_version }}

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest Siege version
        id: get-version
        run: |
          LATEST_VERSION=$(curl -s https://download.joedog.org/siege/ | grep -oP 'siege-\K[0-9.]+(?=\.tar\.gz)' | sort -V | tail -n 1)
          echo "latest_version=${LATEST_VERSION}" >> "$GITHUB_OUTPUT"
          echo "major_version=$(echo ${LATEST_VERSION} | cut -d. -f1)" >> "$GITHUB_OUTPUT"
          echo "minor_version=$(echo ${LATEST_VERSION} | cut -d. -f1-2)" >> "$GITHUB_OUTPUT"

      - name: Display the latest version
        run: |
          echo "The latest version of Siege is ${{ steps.get-version.outputs.latest_version }}"
          echo "The latest major version of Siege is ${{ steps.get-version.outputs.major_version }}"
          echo "The latest minior version of Siege is ${{ steps.get-version.outputs.minor_version }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          load: true
          tags: |
            ttyse/siege:${{ steps.get-version.outputs.latest_version }}
          build-args: |
            SIEGE_VERSION=${{ steps.get-version.outputs.latest_version }}
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@3.0.0
        with:
          support-path: "$HOME/.local/share/bats-support"
          assert-path: "$HOME/.local/share/bats-assert"
          detik-path: "$HOME/.local/share/detik-path"
          file-path: "$HOME/.local/share/bats-file"

      - name: Run BATS Container tests
        id: bats-container-tests
        run: |
          docker run --rm \
            -e TERM=linux \
            -e BATS_LIB_PATH=/bats \
            -v "${{ github.workspace }}/tests:/tests:ro" \
            -v "${HOME}/.local/share:/bats:ro" \
            --entrypoint=/bats/bin/bats \
            ttyse/siege:${{ steps.get-version.outputs.latest_version }} \
            /tests

      - name: Save Build Cache
        uses: actions/cache/save@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-build-cache

  push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main' # Only run if tests pass and branch is main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Restore Build Cache
        uses: actions/cache/save@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-build-cache
          restore-keys: |
            ${{ runner.os }}-docker-build-cache

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ttyse/siege:${{ needs.get-version.outputs.latest_version }}
            ttyse/siege:${{ needs.get-version.outputs.major_version }}
            ttyse/siege:${{ needs.get-version.outputs.minor_version }}
            ttyse/siege:latest
          build-args: |
            SIEGE_VERSION=${{ needs.get-version.outputs.latest_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
